server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: ${SPRING_CONFIG_IMPORT}
  cloud:
    config:
      enabled: true
      fail-fast: false
      profile: ${SPRING_PROFILES_ACTIVE}
      client:
        oauth2:
          client-id: ${SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_CLIENT_ID}
          client-secret: ${SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_CLIENT_SECRET}
          access-token-uri: ${SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_ACCESS_TOKEN_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      client:
        registration:
          eda:
            authorization-grant-type: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EDA_AUTHORIZATION_GRANT_TYPE}
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EDA_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EDA_CLIENT_SECRET}
            provider: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EDA_PROVIDER}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EDA_REDIRECT_URI}
            scope: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_EDA_REDIRECT_SCOPE}
        provider:
          eda:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_EDA_AUTHORIZATION_URI}
            issuer-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_EDA_ISSUER_URI}
            token-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_EDA_TOKEN_URI}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_EDA_USER_INFO_URI}
            user-name-attribute: ${SPRING_SECURITY_OAUTH2_PROVIDER_EDA_USER_NAME_ATTRIBUTE}