server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: ${SPRING_CONFIG_IMPORT}
  cloud:
    config:
      enabled: true
      fail-fast: false
      profile: ${SPRING_PROFILES_ACTIVE}
      client:
        oauth2:
          client-id: ${SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_CLIENT_ID}
          client-secret: ${SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_CLIENT_SECRET}
          access-token-uri: ${SPRING_CLOUD_CONFIG_CLIENT_OAUTH2_ACCESS_TOKEN_URI}