services:
  # MySQL
  mysql:
    container_name: eda-mysql-service
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    env_file:
        - ./environments/env.docker
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
