services:
  # MySQL
  mysql:
    container_name: eda-mysql8
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  # CloudDBeaver
  cloudbeaver:
    container_name: eda-cloudbeaver
    image: dbeaver/cloudbeaver:latest
    ports:
      - 8978:8978
    volumes:
      - ./data/cloudbeaver:/home/cloudbeaver/.dbeaver
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
