services:
  service-discovery-service:
    container_name: eda-service-discovery-service
    image: service-discovery-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8002:8002
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://host.docker.internal:8002/eureka/
      - EUREKA_INSTANCE_HOSTNAME=localhost
      - SERVER_PORT=8002
      - SPRING_CONFIG_IMPORT=configserver:http://host.docker.internal:8001
      - SPRING_PROFILES_ACTIVE=local
