services:
  service-discovery-service:
    container_name: eda-service-discovery-service
    image: service-discovery-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8002:8002
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
        - ./environments/env.docker
