services:
  admin-service:
    container_name: eda-admin-service
    image: admin-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8005:8005"
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./environments/env.local