services:
  config-service:
    container_name: eda-config-service
    image: config-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./environments/env.local