services:
  config-service:
    container_name: eda-config-service
    image: config-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://host.docker.internal:8002/eureka/
      - EUREKA_INSTANCE_HOSTNAME=localhost
      - SERVER_PORT=8001
      - SPRING_CLOUD_SERVER_NATIVE_SEARCH_LOCATIONS=classpath:/configuration-files
      - SPRING_PROFILES_ACTIVE=local
