services:
  config-service:
    container_name: eda-config-service
    image: config-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - SPRING_PROFILES_ACTIVE=local
