management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
