services:
  api-gateway-service:
    container_name: eda-api-gateway-service
    image: api-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8003:8003"
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./environments/env.docker
