services:
  api-gateway-service:
    container_name: eda-api-gateway-service
    image: api-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8003:8003
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_CONFIG_IMPORT=configserver:http://host.docker.internal:8001
