services:
  api-gateway-service:
    container_name: eda-api-gateway-service
    image: api-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8003:8003"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://host.docker.internal:8002/eureka/
      - EUREKA_INSTANCE_HOSTNAME=localhost
      - SERVER_PORT=8003
      - SPRING_CONFIG_IMPORT=configserver:http://host.docker.internal:8001
      - SPRING_PROFILES_ACTIVE=local
